matrix:
  include:
    - env: PLATFORM=debian7
    - env: PLATFORM=debian8
    - env: PLATFORM=debian9

sudo: required

dist: trusty

services:
  - docker

language: python

addons:
  apt:
    packages:
      - vagrant
      - build-essential
      - python-dev
      - libffi-dev
      - libssl-dev

install:
  - pip install ansible

script:
  - vagrant status
  - vagrant up --provider docker $PLATFORM
  - vagrant status

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
