matrix:
  include:
    - env: PLATFORM=debian7
    - env: PLATFORM=debian8
    - env: PLATFORM=debian9

sudo: required

dist: trusty

services:
  - docker

language: python

before_install:
  - sudo pt-get -qq update
  - sudo pt-get install -y --no-install-recommends vagrant build-essential python-pip python-dev libffi-dev libssl-dev
  - sudo ip install ansible
  - vagrant up $PLATFORM
  - vagrant provision $PLATFORM

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
