matrix:
  include:
    - env: PLATFORM=debian7
    - env: PLATFORM=debian8
    - env: PLATFORM=debian9

sudo: required

dist: trusty

services:
  - docker

language: python

addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libffi-dev
      - libssl-dev

before_install:
  - wget https://releases.hashicorp.com/vagrant/1.9.5/vagrant_1.9.5_x86_64.deb
  - sudo dpkg -i vagrant_1.9.5_x86_64.deb

install:
  - pip install ansible

script:
  - vagrant status
  - vagrant up $PLATFORM
  - vagrant status
